target_samples = "input/monoclonal_samples.txt"
min_depth = 5
min_ratio = 0.7
min_r1_r2 = 3.0
min_maf = 0.01
min_site_nonmissing = 0.3
filter_column_pass_only = true
major_minor_alleles_must_be_snps = true
nonmissing_rates= [
    [0.31, 0.155],
    [0.35, 0.175],
    [0.41, 0.205],
    [0.45, 0.225],
    [0.51, 0.255],
    [0.55, 0.275],
    [0.61, 0.305],
    [0.65, 0.325],
    [0.71, 0.355],
    [0.75, 0.375],
    [0.81, 0.405],
    [0.85, 0.45],
    [0.85, 0.50],
    [0.85, 0.55],
    [0.85, 0.60],
    [0.85, 0.65],
    [0.90, 0.70],
    [0.90, 0.80],
]
